name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Inject Secrets
        uses: actions/github-script@v6
        env:
          FB_KEY: ${{ secrets.FIREBASE_KEY }}
          GR_KEY: ${{ secrets.MY_GROQ_KEY }}
        with:
          script: |
            const fs = require('fs');
            let html = fs.readFileSync('index.html', 'utf8');
            
            // الاستبدال باستخدام كلماتك الخاصة
            html = html.split('FIREBASE_API_KEY_PLACEHOLDE').join(process.env.FB_KEY);
            html = html.split('GQ_AB').join(process.env.GR_KEY);
            
            fs.writeFileSync('index.html', html);

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          cname: rga.best
          force_orphan: true
